apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
  namespace: demo
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-80
    nodePort: 30030
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phpmyadmin
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}